// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateChampionshipRoomReducer from "../create_championship_room_reducer";
import CreateLobbyReducer from "../create_lobby_reducer";
import CreatePracticeReducer from "../create_practice_reducer";
import ForfeitReducer from "../forfeit_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import KickPlayerReducer from "../kick_player_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import RematchReducer from "../rematch_reducer";
import RestoreAccountReducer from "../restore_account_reducer";
import SendChatReducer from "../send_chat_reducer";
import SendEmoteReducer from "../send_emote_reducer";
import SetCharacterReducer from "../set_character_reducer";
import SetInputReducer from "../set_input_reducer";
import SetLobbySettingsReducer from "../set_lobby_settings_reducer";
import SetNameReducer from "../set_name_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartMatchReducer from "../start_match_reducer";

export type CreateChampionshipRoomParams = __Infer<typeof CreateChampionshipRoomReducer>;
export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type CreatePracticeParams = __Infer<typeof CreatePracticeReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type KickPlayerParams = __Infer<typeof KickPlayerReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type RematchParams = __Infer<typeof RematchReducer>;
export type RestoreAccountParams = __Infer<typeof RestoreAccountReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SendEmoteParams = __Infer<typeof SendEmoteReducer>;
export type SetCharacterParams = __Infer<typeof SetCharacterReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;
export type SetLobbySettingsParams = __Infer<typeof SetLobbySettingsReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;

