// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  mode: __t.u8(),
  courseId: __t.u8(),
  isPublic: __t.bool(),
  botFill: __t.bool(),
  botLevel: __t.u8(),
  stages: __t.u8(),
  gravityMul: __t.f32(),
  gripMul: __t.f32(),
  speedMul: __t.f32(),
  airMul: __t.f32(),
};
