// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostId: __t.identity().name("host_id"),
  mode: __t.u8(),
  status: __t.u8(),
  vsBot: __t.bool().name("vs_bot"),
  courseId: __t.u8().name("course_id"),
  seed: __t.u32(),
  stage: __t.u8(),
  stages: __t.u8(),
  botFill: __t.bool().name("bot_fill"),
  botLevel: __t.u8().name("bot_level"),
  botSkill: __t.u8().name("bot_skill"),
  championName: __t.string().name("champion_name"),
  createdAt: __t.timestamp().name("created_at"),
  isPublic: __t.bool().name("is_public"),
  gravityMul: __t.f32().name("gravity_mul"),
  gripMul: __t.f32().name("grip_mul"),
  speedMul: __t.f32().name("speed_mul"),
  airMul: __t.f32().name("air_mul"),
  championshipLeg: __t.u64().name("championship_leg"),
});
