// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  raceId: __t.u64().name("race_id"),
  courseId: __t.u8().name("course_id"),
  place: __t.u8(),
  riders: __t.u8(),
  timeTicks: __t.u32().name("time_ticks"),
  ranked: __t.bool(),
  mmrBefore: __t.u16().name("mmr_before"),
  mmrAfter: __t.u16().name("mmr_after"),
  xpBefore: __t.u32().name("xp_before"),
  xpGained: __t.u32().name("xp_gained"),
  levelAfter: __t.u16().name("level_after"),
  topSpeed: __t.u16().name("top_speed"),
  tricks: __t.u16(),
  endedBy: __t.u8().name("ended_by"),
  playedAt: __t.timestamp().name("played_at"),
});
