// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  lobbyId: __t.u64().name("lobby_id"),
  raceId: __t.u64().name("race_id"),
  characterId: __t.u8().name("character_id"),
  bikeId: __t.u8().name("bike_id"),
  s: __t.f32(),
  n: __t.f32(),
  v: __t.f32(),
  yaw: __t.f32(),
  z: __t.f32(),
  vz: __t.f32(),
  pitch: __t.f32(),
  lean: __t.f32(),
  boost: __t.u16(),
  boosting: __t.bool(),
  airTicks: __t.u16().name("air_ticks"),
  crashTicks: __t.u8().name("crash_ticks"),
  trickKind: __t.u8().name("trick_kind"),
  trickSpin: __t.f32().name("trick_spin"),
  slip: __t.f32(),
  place: __t.u8(),
  finishTicks: __t.u32().name("finish_ticks"),
  cupPoints: __t.u16().name("cup_points"),
  dirX: __t.i8().name("dir_x"),
  dirY: __t.i8().name("dir_y"),
  btn: __t.u8(),
  hopTicks: __t.u8().name("hop_ticks"),
  fxKind: __t.u8().name("fx_kind"),
  fxTicks: __t.u8().name("fx_ticks"),
  online: __t.bool(),
  isBot: __t.bool().name("is_bot"),
  spectator: __t.bool(),
  ready: __t.bool(),
  kicked: __t.bool(),
  botSkill: __t.u8().name("bot_skill"),
  topV: __t.f32().name("top_v"),
  tricksDone: __t.u16().name("tricks_done"),
});
