// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  stage: __t.u8(),
  state: __t.u8(),
  courseId: __t.u8().name("course_id"),
  seed: __t.u32(),
  length: __t.f32(),
  startTicks: __t.u16().name("start_ticks"),
  elapsed: __t.u32(),
  finished: __t.u8(),
  riders: __t.u8(),
  leaderName: __t.string().name("leader_name"),
  winnerName: __t.string().name("winner_name"),
  cutoff: __t.u32(),
  haltUntil: __t.u64().name("halt_until"),
  haltName: __t.string().name("halt_name"),
  haltedAt: __t.u64().name("halted_at"),
});
