// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  identity: __t.identity(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string(),
  characterId: __t.u8(),
  bikeId: __t.u8(),
  xp: __t.u32(),
  level: __t.u16(),
  mmr: __t.u16(),
  peakMmr: __t.u16(),
  ranked: __t.u16(),
  rankedWins: __t.u16(),
  casual: __t.u16(),
  casualWins: __t.u16(),
  streak: __t.i16(),
  bestStreak: __t.u16(),
  quits: __t.u16(),
  rev: __t.u32(),
  races: __t.u16(),
  wins: __t.u16(),
  podiums: __t.u16(),
  botWins: __t.u16(),
  tricks: __t.u32(),
  topSpeed: __t.u16(),
  cupWins: __t.u16(),
  courseWins: __t.u32(),
  cupStage: __t.u8(),
  cupRound: __t.u8(),
};
