// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  uid: __t.string(),
  provider: __t.u8(),
  displayName: __t.string(),
  characterId: __t.u8(),
  bikeId: __t.u8(),
  xp: __t.u32(),
  level: __t.u16(),
  mmr: __t.u16(),
  peakMmr: __t.u16(),
  ranked: __t.u16(),
  rankedWins: __t.u16(),
  casual: __t.u16(),
  casualWins: __t.u16(),
  streak: __t.i16(),
  bestStreak: __t.u16(),
  quits: __t.u16(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  rev: __t.u32(),
  races: __t.u16(),
  wins: __t.u16(),
  podiums: __t.u16(),
  botWins: __t.u16(),
  tricks: __t.u32(),
  topSpeed: __t.u16(),
  cupWins: __t.u16(),
  courseWins: __t.u32(),
  cupStage: __t.u8(),
  cupRound: __t.u8(),
});
export type Account = __Infer<typeof Account>;

export const Chat = __t.object("Chat", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  senderName: __t.string(),
  emote: __t.bool(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type Chat = __Infer<typeof Chat>;

export const ChatGuard = __t.object("ChatGuard", {
  identity: __t.identity(),
  lastAt: __t.u64(),
  burst: __t.u8(),
  mutedUntil: __t.u64(),
});
export type ChatGuard = __Infer<typeof ChatGuard>;

export const GraceTimer = __t.object("GraceTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  raceId: __t.u64(),
});
export type GraceTimer = __Infer<typeof GraceTimer>;

export const LegResult = __t.object("LegResult", {
  id: __t.u64(),
  legId: __t.u64(),
  placings: __t.array(__t.identity()),
  names: __t.array(__t.string()),
  finishedAt: __t.timestamp(),
});
export type LegResult = __Infer<typeof LegResult>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  code: __t.string(),
  hostId: __t.identity(),
  mode: __t.u8(),
  status: __t.u8(),
  vsBot: __t.bool(),
  courseId: __t.u8(),
  seed: __t.u32(),
  stage: __t.u8(),
  stages: __t.u8(),
  botFill: __t.bool(),
  botLevel: __t.u8(),
  botSkill: __t.u8(),
  championName: __t.string(),
  createdAt: __t.timestamp(),
  isPublic: __t.bool(),
  gravityMul: __t.f32(),
  gripMul: __t.f32(),
  speedMul: __t.f32(),
  airMul: __t.f32(),
  championshipLeg: __t.u64(),
});
export type Lobby = __Infer<typeof Lobby>;

export const MyRaceLog = __t.object("MyRaceLog", {});
export type MyRaceLog = __Infer<typeof MyRaceLog>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  lobbyId: __t.u64(),
  raceId: __t.u64(),
  characterId: __t.u8(),
  bikeId: __t.u8(),
  s: __t.f32(),
  n: __t.f32(),
  v: __t.f32(),
  yaw: __t.f32(),
  z: __t.f32(),
  vz: __t.f32(),
  pitch: __t.f32(),
  lean: __t.f32(),
  boost: __t.u16(),
  boosting: __t.bool(),
  airTicks: __t.u16(),
  crashTicks: __t.u8(),
  trickKind: __t.u8(),
  trickSpin: __t.f32(),
  slip: __t.f32(),
  place: __t.u8(),
  finishTicks: __t.u32(),
  cupPoints: __t.u16(),
  dirX: __t.i8(),
  dirY: __t.i8(),
  btn: __t.u8(),
  hopTicks: __t.u8(),
  fxKind: __t.u8(),
  fxTicks: __t.u8(),
  online: __t.bool(),
  isBot: __t.bool(),
  spectator: __t.bool(),
  ready: __t.bool(),
  kicked: __t.bool(),
  botSkill: __t.u8(),
  topV: __t.f32(),
  tricksDone: __t.u16(),
  driftDir: __t.i8(),
  driftCharge: __t.u16(),
  grindTicks: __t.u16(),
});
export type Player = __Infer<typeof Player>;

export const Race = __t.object("Race", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  stage: __t.u8(),
  state: __t.u8(),
  courseId: __t.u8(),
  seed: __t.u32(),
  length: __t.f32(),
  startTicks: __t.u16(),
  elapsed: __t.u32(),
  finished: __t.u8(),
  riders: __t.u8(),
  leaderName: __t.string(),
  winnerName: __t.string(),
  cutoff: __t.u32(),
  haltUntil: __t.u64(),
  haltName: __t.string(),
  haltedAt: __t.u64(),
});
export type Race = __Infer<typeof Race>;

export const RaceLog = __t.object("RaceLog", {
  id: __t.u64(),
  identity: __t.identity(),
  raceId: __t.u64(),
  courseId: __t.u8(),
  place: __t.u8(),
  riders: __t.u8(),
  timeTicks: __t.u32(),
  ranked: __t.bool(),
  mmrBefore: __t.u16(),
  mmrAfter: __t.u16(),
  xpBefore: __t.u32(),
  xpGained: __t.u32(),
  levelAfter: __t.u16(),
  topSpeed: __t.u16(),
  tricks: __t.u16(),
  endedBy: __t.u8(),
  playedAt: __t.timestamp(),
});
export type RaceLog = __Infer<typeof RaceLog>;

export const ReapTimer = __t.object("ReapTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
});
export type ReapTimer = __Infer<typeof ReapTimer>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  startedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  raceId: __t.u64(),
});
export type TickTimer = __Infer<typeof TickTimer>;

